name: Emre Okcular Personal Website
author: Emre Okcular
title: null
email: emreokcular@gmail.com
image: https://www.okcular.com.tr/resources/image.png
teaser: https://www.okcular.com.tr/resources/image.png